Statistics for users
sopra-fs24-group-41/sopra-fs24-group-41-server pull request #187
Opened 2024-05-05 17:32 UTC by Aquamarine-12

Added the following statistics for each User:
- number of combinations they made;
- number of new words they generated (i.e., added to the DB as a result of their combinations made)
- rarest word found (in terms of reachability when that word was generated)

2024-05-06 00:57 UTC, Tmmn commented
Did you also get this?
```
Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: ch.uzh.ifi.hase.soprafs24.entity.Combination["word1"]->ch.uzh.ifi.hase.soprafs24.entity.Word["combinations"]->org.hibernate.collection.internal.PersistentBag[0]->ch.uzh.ifi.hase.soprafs24.entity.Combination["word1"]->...
```
I will try again tomorrow to find out why I got this

2024-05-06 07:27 UTC, Aquamarine-12 commented
> Did you also get this?
> 
> ```
> Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Infinite recursion (StackOverflowError); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: ch.uzh.ifi.hase.soprafs24.entity.Combination["word1"]->ch.uzh.ifi.hase.soprafs24.entity.Word["combinations"]->org.hibernate.collection.internal.PersistentBag[0]->ch.uzh.ifi.hase.soprafs24.entity.Combination["word1"]->...
> ```
> 
> I will try again tomorrow to find out why I got this

Huh, I didn't get this.

2024-05-06 08:57 UTC, Tmmn requested changes

2024-05-06 08:57 UTC, Tmmn commented on src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserGetDTO.java
> +    private Word rarestWordFound;
change this from Type Word to WordDTO and the infinite recursion goes away

2024-05-06 09:25 UTC, Aquamarine-12 commented on src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserGetDTO.java
> +    private Word rarestWordFound;
Why though?

2024-05-06 09:28 UTC, Tmmn commented on src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserGetDTO.java
> +    private Word rarestWordFound;
as soon as the user has a word and jackson tries to generate a json string for the UserGetDTO. it goes from word to combinations, then back to the word because it was involved in combinations and then back to combinations etc.

2024-05-06 19:53 UTC, Tmmn approved these changes
works 🔨✅

2024-05-07 07:32 UTC, JacquelineUlken requested changes

2024-05-07 07:32 UTC, JacquelineUlken commented on src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
> +        Word resultWord = combination.getResult();
Why are you passing the combination here if you only need the result anyway?

2024-05-07 07:32 UTC, JacquelineUlken commented on src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
> +        updatePlayerStatistics(player, combinationService.getCombination(words.get(0), words.get(1)));
just pass result, don't get the combination again

2024-05-07 07:32 UTC, JacquelineUlken commented on src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
> +        Lobby lobby = winner.getLobby();
Don't get the lobby again, just pass the lobby that you already have in the play method

2024-05-07 07:32 UTC, JacquelineUlken commented on src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
> +            User user = player.getUser();
Suggestion, but you might disagree and it's fine if you don't change this: Perhaps let the Player handle all of this. Give the player a method like `addWins(int wins)`, in that method the player checks themselves if they have a user, and if so, they add wins to their user and otherwise do nothing. Same with losses. 

This would clean up the code here a bit.

2024-05-07 07:32 UTC, JacquelineUlken commented on src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
I would add two utilitty methods here: addWins(int wins) and addLosses(int losses), so that you don't always have to do the whole user.setWins(user.getWins() + 1).

2024-05-07 07:32 UTC, JacquelineUlken commented on src/main/java/ch/uzh/ifi/hase/soprafs24/service/WordService.java
> +    public boolean checkUniqueWord(Word word) {
I'm not sure I understand what this does. When the player makes a new combination, the result is automatically saved, so in here it will always find the word. 

Then you're checking the reachability. I get that if the reachability is equal to 1/(2^depth) then there is exactly one combination that leads to this word. However, you later use this to increase the "discovered words" counter. But just because the combination is unique, doesn't mean this is a newly discovered word. The player could've just made this existing combination, which was already discovered.

2024-05-12 20:32 UTC, Tmmn commented on src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Player.java
> +    }
maybe you want to rename to something like addWinsToUser and addLossesToUser

2024-05-15 06:20 UTC, JacquelineUlken approved these changes

2024-05-15 09:55 UTC, merged